import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg font-main ml-5 ">
        {/* Navbar */}
        <div className="mt-4 sticky flex items-center">
          <a href="/">
            <div class="font-logo-purple text-5xl">onebookaweek</div>
          </a>
          <div class="ml-5 flex items-center">
            <a className="font-logo ml-28 text-3xl cursor-pointer">
              <h2>the challenge</h2>
            </a>
            <a className="font-logo ml-28 text-3xl cursor-pointer">
              <h2>blog</h2>
            </a>
            <a className="font-logo ml-28 text-3xl cursor-pointer">
              <h2>discussion</h2>
            </a>
          </div>
        </div>

        <main className="mt-10">{children}</main>
      </body>
    </html>
  );
}
