import "./globals.css";
import Cursor from "@/components/Cursor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="cursor-none" lang="en">
      <body className="bg font-main overflow-x-hidden">
        {/* Cursor BS */}
        <Cursor />

        {/* Navbar */}
        <div className="pb-3 border-b-2 border-b-gray-500 bg">
          <div className="mt-4 sticky flex items-center ml-5 bg">
            <a>
              <div className="font-logo-purple text-5xl ml-3 hover:tracking-widest transition-all">onebookaweek</div>
            </a>
            <div className="ml-0 flex items-center">
              <a className="font-logo ml-28 text-3xl hover:tracking-wide transition-all">
                <h2>the challenge</h2>
              </a>
              <a className="font-logo ml-28 text-3xl hover:tracking-wide transition-all">
                <h2>weeks</h2>
              </a>
              <a className="font-logo ml-28 text-3xl hover:tracking-wide transition-all">
                <h2>discussion</h2>
              </a>
            </div>
          </div>
        </div>

        {/* Actual Content */}
        <main className="mt-10">{children}</main>

        {/* Footer */}
        <div>
          <br />
          <hr>
          </hr>
          <h1 className="ml-10 mt-5 mb-5 font-bold font-main text-white text-center">A Lakshya Jain Project ©</h1>
        </div>
      </body>
    </html>
  );
}
